name: MusikBot
version: 1.2.2
author: Steviebeenz
description: Discord Music Bot

main: io.github.steviebeenz.musikbot.Main
loadbefore: [AutoUpdaterAPI]
permissions:
  MusikBot.update:
    description: Allows auto updater to run on join
    default: op
